# -*- coding: utf-8 -*-
{
    "name": """Multi-website support in Security Rules""",
    "summary": """Provide access depending on current website""",
    "category": "Access",
    # "live_test_url": "",
    "images": [],
    "version": "10.0.1.3.1",
    "application": False,
    "author": "IT-Projects LLC, Ildar Nasyrov",
    "support": "apps@itpp.dev",
    "website": "https://twitter.com/OdooFree",
    "license": "Other OSI approved licence",  # MIT
    "depends": ["web_website"],
    "external_dependencies": {"python": [], "bin": []},
    "data": ["views/ir_rule_views.xml"],
    "qweb": [],
    "demo": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
