{
    "name": "Clear access rights button",
    "summary": """Useful tool to reset user rights""",
    "vesion": "11.0.1.0.0",
    "author": "IT-Projects LLC, Ivan Yelizariev",
    "license": "LGPL-3",
    "support": "apps@it-projects.info",
    "website": "https://it-projects.info",
    "category": "Access",
    "depends": ["base"],
    "external_dependencies": {"python": [], "bin": []},
    "data": ["views.xml",],
    "demo": [],
    "installable": False,
    "auto_install": False,
}
